services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./tmp:/app/tmp
    environment:
      DATABASE_URL: postgis://postgres:password@db:5432/earthquake_app_development
      RAILS_ENV: development
      API_JWT_SECRET: random
    entrypoint: ["/app/bin/docker-entrypoint"]
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: earthquake_app_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
